アプリケーションを完成させよう2/第5章/meshiterro/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'post_images#index'
  resources :post_images, only:[:new, :create, :index, :show, :destroy] do
  	resource :favorites, only:[:create, :destroy]
  	resource :post_comments, only:[:create, :destroy]
  end
  resources :users,only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

アプリケーションを完成させよう2/第5章/meshiterro/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

アプリケーションを完成させよう2/第5章/meshiterro/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@post_images = @user.post_images.page(params[:page]).reverse_order
  end
end

アプリケーションを完成させよう2/第5章/meshiterro/app/views/post_images/index.html.erb
<!-- http://localhost:3000/ -->

<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">
          <div class="masonry-gutter"></div>
            <% @post_images.each do |post_image| %>
            <div class="masonry-block">
              <div class="block block-image v1">
                <div class="block-image">
                  <div class="view view-first">
                   <%= link_to post_image_path(post_image.id) do %>
                    <%= attachment_image_tag post_image, :image %>
                   <% end %>
                  </div>
                </div>
                <div class="block-content">
                  <%= image_tag('sample-author1.jpg', class: "img-circle pull-left profile-thumb") %>
                  <h3 class="block-title">
                  <%= link_to post_image_path(post_image.id) do %>
                     <i class="fa fa-map-marker"></i><%= post_image.shop_name %>
                  <% end %>
                  </h3>
                  <p><%= post_image.caption %></p>
                  <ul class="inline-meta">
                    <li>By
                      <%= post_image.user.name %>
                    </li>
                    <li>
                    <%= link_to "#{post_image.post_comments.count}コメント",post_image_path(post_image.id) %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <% end %>
            <%= paginate @post_images, class: "paginate" %>
        </div>
      </div>
    </div>
  </div>
</section>

アプリケーションを完成させよう2/第5章/meshiterro/app/views/post_images/show.html.erb
<!-- http://localhost:3000/post_images/# -->

<section class="sct-color-1 slice">
  <div class="container">
    <div class="row">
      <div class="col-md-12 post_images_container">
        <div class="post-item">

          <div class="post-meta-top">
            <div class="post-image">
              <%= attachment_image_tag @post_image, :image %>
            </div>
          </div>

          <div class="post-content">
            <h2 class="post-title"><%= @post_image.shop_name %></h2>
            <ul class="meta-info-cells v4 float-wrapper">
              <li>
                <i class="fa fa-user"></i>By
                <a href="#"><%= @post_image.user.name %></a>
              </li>
              <li>
                <i class="fa fa-calendar"></i><%= @post_image.created_at.strftime('%Y/%m/%d') %>
              </li>
             <% if @post_image.favorited_by?(current_user) %>
              <li>
                <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
                　<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                　<%= @post_image.favorites.count %>いいね
                <% end %>
              </li>
             <% else %>
              <li>
              　<%= link_to post_image_favorites_path(@post_image), method: :post do %>
                　<i class="fa fa-heart-o" aria-hidden="true"></i>
                　<%= @post_image.favorites.count %>いいね
                <% end %>
              <li>
              <% end %>
                <i class="fa fa-comment"></i>
                <a href="#comments"><%= @post_image.post_comments.count %></a>
              </li>
              <li>
               <% if @post_image.user == current_user %>
                <%= link_to "削除", post_image_path(@post_image), method: :delete %>
               <% end %>
              </li>
            </ul>
            <div class="post-content-inner mt-20">
              <p><%= @post_image.caption %></p>
            </div>
          </div>

          <div class="comment-list bt style-2" id="comments">
            <div class="float-wrapper">
              <h2 class="comment-count"><%= @post_image.post_comments.count %>件コメント</h2>
            </div>
            <ol>
             <% @post_image.post_comments.each do |post_comment| %>
              <li class="comment">
                <div class="comment-body bb">
                  <div class="comment-avatar">
                    <div class="avatar">
                      <!-- <img src="images/sample-author1.jpg"> -->
                      <%= image_tag('sample-author1.jpg',style: "width: 60px; height: 60px;") %>
                    </div>
                  </div>
                  <div class="comment-text">
                    <div class="comment-author clearfix">
                      <a href="#" class="link-author"><%= post_comment.user.name %></a>
                      <span class="comment-meta">
                        <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
                      </span>
                    </div>
                    <div class="comment-entry"><%= post_comment.comment %></div>
                  </div>
                </div>
              </li>
             <% end %>
            </ol>
          </div>
          <hr>

          <!-- Add comment section -->
          <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
            <h3 class="section-title left">
              <span>コメント</span>
            </h3>
          </div>
          <!-- <form class="mt-20"> -->
           <%= form_for [@post_image, @post_comment] do |f| %>
            <div class="row">
              <div class="col-sm-12">
                <%= f.text_area :comment, rows:"5", class:"form-control",placeholder:"コメントをここに" %>
              </div>
            </div>
            <%= f.submit"送信する", class:"btn btn-lg btn-base-1 mt-20 pull-right" %>
           <% end %>
          <!-- </form> -->

        </div>
      </div>
    </div>
  </div>
</section>